- name: Setup Pages
    id: pages
    uses: actions/configure-pages@v5

  - name: Setup Hugo
    uses: peaceiris/actions-hugo@v3
    with:
      # Use 'latest' or specify a version like '0.128.0'
      hugo-version: 'latest'
      # Essential for themes that use SASS/SCSS or modern features
      extended: true

  - name: Build Hugo Site
    # The baseURL is configured via the GitHub Pages URL output, ensuring
    # assets links are correct in the deployed environment.
    run: hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

  - name: Upload artifact
    uses: actions/upload-pages-artifact@v3
    with:
      # The path to Hugo's default output directory
      path: ./public

  - name: Deploy to GitHub Pages
    id: deployment
    uses: actions/deploy-pages@v4
